### ISSUE TITLE
No similar requirements found after adding new requirement

### ISSUE THREAD

**Issue by AndreaMussmann** [OpenReqEU/similarity-detection#3]
While testing I ran into the following issue: when using addRequirement to add a new requirement to a model (id not yet in model), the model doesn't find similar requirements anymore, even if it did before the add.

What I did to reproduce the error:
1. used BuildModelAndCompute to build a model for company: TEST with the two requirements
``
{
  "requirements": [
    {
      "id": "1",
      "name": "Check swagger version.",
      "text": "The swagger version is deprecated. Please update the service asap."
    },
    {
      "id": "2",
      "name": "Check swagger version.",
      "text": "The swagger version is deprecated. Please update the service asap."
    }
  ]
}
``

and parameters: 
- compare: true
- company: TEST
- threshold: 0.1
- url: http://localhost:9406/upload/PostResult

Outcome (as expected): 1 dependency
``
{
  "status": 200,
  "dependencies": [
    {
      "toid": "2",
      "dependency_type": "similar",
      "dependency_score": 1,
      "description": [
        "Similarity-UPC"
      ],
      "fromid": "1",
      "status": "proposed"
    }
  ]
}
``
2. used AddRequirements to add a requirement to the model for company TEST
``
{
  "requirements": [
    { 
      "id": "3",  
      "name": "Check swagger version.",
      "text": "The swagger version is deprecated. Please update the service asap."
    }
  ]
}
``
3. used Project compare option
``
{
  "projects": [
    {
      "id": "TEST-Project",
      "specifiedRequirements": [
        "1","2","3"
      ]
    }
  ]
}
``
Expected Outcome: 3 dependencies 
Actual Outcome: no dependencies
{}

**Comment by FerranAgulloLopez** [comment]
The problem has to do with all the words appearing in all the requirements of the model (the two input requirements are the same). The algorithm, therefore, considers that none of the words contribute anything to compute the similarity between different requirements.

However, there was a bug in the component because the output in both cases should be empty. This bug is fixed with the commit "a157867..." and was caused by not preventing the occurrence of negative values in the model stored in the database. So, the expected output with the last commit is an empty dependency array in both cases.

PD: The empty json bug that appears in the second output was fixed in the commit "1f00cb39c...". An empty dependency array is now returned: "{"status": 200,"dependencies": []}"

**Comment by AndreaMussmann** [comment]
Thank you for clarifying.
